"""Central Pydantic models representing the documented CarTech data model."""

from app.models.enums import (
    FieldStatus,
    InspectionResult,
    PropulsionType,
    RdksType,
    RimCategory,
    ServiceStatus,
    ServiceType,
    TireConditionType,
    TirePosition,
    TireSetRole,
    TireType,
    VisualInspectionComponent,
    VisualInspectionResult,
    WheelBoltConfiguration,
)
from app.models.schemas import (
    BrakeDiscMeasurement,
    Customer,
    CustomerSignature,
    ServiceRecord,
    ServiceTireSet,
    Tire,
    TireChangeDetails,
    TireCondition,
    TireInspection,
    TireSet,
    Vehicle,
    VisualInspection,
)
from app.models.review import calculate_review_required

__all__ = [
    "BrakeDiscMeasurement",
    "calculate_review_required",
    "Customer",
    "CustomerSignature",
    "FieldStatus",
    "InspectionResult",
    "PropulsionType",
    "RdksType",
    "RimCategory",
    "ServiceRecord",
    "ServiceStatus",
    "ServiceTireSet",
    "ServiceType",
    "Tire",
    "TireChangeDetails",
    "TireCondition",
    "TireConditionType",
    "TireInspection",
    "TirePosition",
    "TireSet",
    "TireSetRole",
    "TireType",
    "Vehicle",
    "VisualInspection",
    "VisualInspectionComponent",
    "VisualInspectionResult",
    "WheelBoltConfiguration",
]
